name: Bohuslav Rattay
analytics: {}
github: true
description: Conductor
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
author: {}
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/6f5f4e66-ec8a-4d50-ab1d-019b6a3a0eea.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/6f5f4e66-ec8a-4d50-ab1d-019b6a3a0eea.jpg
    metadata:
      author: []
      '@context': 'http://schema.org'
      keywords: []
      '@type': MediaObject
      publisher:
        favicon: null
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      app_links: []
      related: []
      description: ''
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
navigation:
  - id: 9bec7049-a4da-4d5e-84e8-229d040e05e0
    name: BIOGRAPHY
    type: content
  - id: ba9aa43c-9111-480e-83c3-8c206834bcb7
    name: 2016/2017 SEASON
    type: content
layout_spectrum: 1
color:
  lightness: 0.4561289399336692
  brandColors:
    - '#1A1F2B'
    - '#30395C'
    - '#4A6491'
    - '#85A5CC'
    - '#D0E4F2'
  saturation: 0.957837709733331
  brandStrength: 0.4681690983468722
  rhythmicContrast: 0.3058056282128512
content_rating:
  adult: false
typography_spectrum: 0.9480101153983891
opengraph: {}
title: BOHUSLAV RATAY
